language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer install -n --dev --prefer-source

script: vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/test-reporter
